"""JSONC overlay / strip / drift-classify for ``preserve_user_keys``.

VSCode ``settings.json`` files are JSONC (JSON with ``//`` and ``/* */``
comments and trailing commas). ruamel.yaml's round-trip mode can't parse
them, so the YAML preservation pipeline doesn't apply.

This module is a thin wrapper over :mod:`json5` (PyPI ``json-five``,
Apache 2.0). JSON5 is a strict superset of JSONC, so VSCode files parse
cleanly; the ``ModelLoader``/``ModelDumper`` pair preserves comments
and formatting on round-trip via ``.wsc_before`` / ``.wsc_after``
attributes attached to every node.

Scope (v1, per ``tracked_files-nen.6``):

- Literal top-level keys only. ``preserve_user_keys`` entries are NOT
  parsed as dotted paths — a key like
  ``"claudeCode.allowDangerouslySkipPermissions"`` is the literal whole
  string, matching VSCode's flat-with-dotted-names convention.
- Top-level user-key values may be any JSON5 scalar (string, number,
  boolean, null). Nested object/array values for user-keys are out of
  scope for v1; tracked as ``tracked_files-nen.6.1``.
- Standard JSONC syntax only: ``//``, ``/* */``, trailing commas. JSON5
  extras (unquoted keys, single-quoted strings, hex literals) are not
  generated by us; they parse but pass through untouched.

Nested-path syntax (``tracked_files-nen.19``):

- Entries in ``preserve_user_keys`` containing ``" > "`` (space-arrow-space)
  are parsed as nested paths whose segments are literal JSON keys.
  Example: ``"[python] > editor.fontSize"``.
- Single-segment names (no separator) keep v1 literal-top-level semantics.
- Missing intermediates on either side are silent skips; a mid-path
  intermediate that exists but isn't an object raises
  :class:`MergeTypeMismatch` with the path prefix in the message.

The exact json-five model API (node classes, field names) is upstream's
business — every reference to it stays inside this module so a future
breaking change in json-five requires a single-module fix.
"""

import json
from collections.abc import Mapping
from pathlib import Path
from typing import Any

# json5 (json-five on PyPI) ships py.typed without resolvable annotations; no stub pkg.
from json5.dumper import ModelDumper, dumps  # type: ignore[import-not-found]
from json5.loader import ModelLoader, loads  # type: ignore[import-not-found]
from json5.model import (  # type: ignore[import-not-found]
    BooleanLiteral,
    DoubleQuotedString,
    Float,
    Identifier,
    Integer,
    JSONArray,
    JSONObject,
    KeyValuePair,
    NullLiteral,
    SingleQuotedString,
)

from setforge.errors import MergeTypeMismatch

PATH_SEPARATOR: str = " > "
"""Segment separator for nested-path entries in ``preserve_user_keys``.

JSONC uses ``" > "`` (space-arrow-space) because VSCode's flat-with-dotted
keys (``claudeCode.allowDangerouslySkipPermissions``) make ``.`` ambiguous
with literal key names. YAML's ``preserve_user_keys`` keeps ``.`` per
``yaml_merge`` — only JSONC paths use this separator.
"""


def _split_path(name: str) -> list[str]:
    """Split a ``preserve_user_keys`` entry into JSON-key segments.

    Single-segment names (no separator) return ``[name]`` — v1 literal
    top-level behavior. Whitespace-only segments are not stripped; the
    Pydantic validator at :class:`setforge.config.TrackedFile` rejects
    malformed paths at config-load time.
    """
    if PATH_SEPARATOR not in name:
        return [name]
    return name.split(PATH_SEPARATOR)


def is_jsonc_file(path: Path) -> bool:
    """True iff ``path`` should be treated as JSONC.

    Heuristic by extension: every ``.json`` file in this codebase is
    JSONC-capable (matches VSCode's behavior — ``.json`` is parsed as
    JSONC there). Tracked Claude ``settings.json`` is plain JSON in
    practice but still parses cleanly through the JSONC pipeline; no
    need for a content sniff.
    """
    return path.suffix == ".json"


def parse_jsonc(text: str) -> Any:
    """Parse JSONC into a plain Python value.

    Comments and formatting are dropped — this return is for drift
    classification (compare a tracked dict vs a live dict), not editing.
    Use :func:`overlay_user_keys` / :func:`strip_user_keys` for
    comment-preserving edits.
    """
    return loads(text)


def overlay_user_keys(
    tracked_text: str,
    live_text: str,
    key_names: list[str],
    deep_key_names: list[str] | None = None,
) -> str:
    """Splice live's top-level user-key values into tracked.

    Shallow mode (``key_names``): for each name, if live has it as a
    top-level key, set tracked's same key to live's value (replacing
    if already present, appending if not).

    Deep mode (``deep_key_names``): for each name, if live's value at
    that name is a JSON object AND tracked's value at the same name is
    also a JSON object, recursively deep-merge — tracked-only sub-keys
    survive, live-only added, scalars take live, lists whole-replaced,
    type mismatches at any depth raise :class:`MergeTypeMismatch`.

    Comments and formatting in tracked are preserved end-to-end across
    both modes. Top-level keys only — names match as literal strings
    against each top-level entry's key text.
    """
    tracked_model = loads(tracked_text, loader=ModelLoader())
    live_value = loads(live_text)
    if not isinstance(live_value, dict):
        return tracked_text
    tracked_top = _require_top_object(tracked_model)
    indent = _detect_indent(tracked_top)
    _overlay_shallow_keys(tracked_top, live_value, key_names, indent)
    _overlay_deep_keys(tracked_top, live_value, deep_key_names or [], indent)
    return dumps(tracked_model, dumper=ModelDumper())


def _overlay_shallow_keys(
    tracked_top: JSONObject,
    live_value: Mapping[str, Any],
    key_names: list[str],
    indent: str,
) -> None:
    """Apply the flat-key and nested-path branches of ``overlay_user_keys``.

    For each name in ``key_names``: multi-segment paths dispatch to
    :func:`_overlay_path`; single-segment names replace or append the
    top-level entry. Lifted from :func:`overlay_user_keys` to keep that
    function under the project's 40-line ceiling — behavior unchanged.
    """
    for name in key_names:
        segments = _split_path(name)
        if len(segments) > 1:
            _overlay_path(tracked_top, live_value, segments, indent)
            continue
        if name not in live_value:
            continue
        new_value_node = _python_to_node(live_value[name])
        new_value_node.wsc_before = [" "]
        idx = _find_key_index(tracked_top, name)
        if idx is not None:
            tracked_top.values[idx] = new_value_node
        else:
            new_key_node = DoubleQuotedString(
                characters=name, raw_value=json.dumps(name)
            )
            new_key_node.wsc_before = [indent]
            tracked_top.keys.append(new_key_node)
            tracked_top.values.append(new_value_node)


def _overlay_deep_keys(
    tracked_top: JSONObject,
    live_value: Mapping[str, Any],
    deep_key_names: list[str],
    indent: str,
) -> None:
    """Apply the deep-merge branch of ``overlay_user_keys``.

    For each name in ``deep_key_names``: append a fresh node when
    tracked lacks the key; otherwise dispatch by node-vs-mapping shape
    to :func:`_deep_merge_jsonobject`, raise :class:`MergeTypeMismatch`
    on dict-vs-non-dict mismatches, or fall back to whole-leaf replace
    for scalar/list. Lifted from :func:`overlay_user_keys` to keep that
    function under the 40-line ceiling — behavior unchanged.
    """
    for name in deep_key_names:
        if name not in live_value:
            continue
        live_sub = live_value[name]
        idx = _find_key_index(tracked_top, name)
        if idx is None:
            new_value_node = _python_to_node(live_sub)
            new_value_node.wsc_before = [" "]
            new_key_node = DoubleQuotedString(
                characters=name, raw_value=json.dumps(name)
            )
            new_key_node.wsc_before = [indent]
            tracked_top.keys.append(new_key_node)
            tracked_top.values.append(new_value_node)
            continue
        src_value_node = tracked_top.values[idx]
        match (src_value_node, live_sub):
            case (JSONObject(), Mapping()):
                _deep_merge_jsonobject(src_value_node, live_sub, name)
            case (JSONObject(), _):
                raise MergeTypeMismatch(
                    f"deep-merge at {name!r} requires dict on both sides; "
                    f"live is {type(live_sub).__name__}"
                )
            case (_, Mapping()):
                raise MergeTypeMismatch(
                    f"deep-merge at {name!r} requires dict on both sides; "
                    f"src is {type(src_value_node).__name__}"
                )
            case _:
                # Mixed scalar/list at top-level deep-key: fall back to
                # whole-leaf replace — live wins, comments on the existing
                # value node are dropped (acceptable for live-wins overlay).
                new_value_node = _python_to_node(live_sub)
                new_value_node.wsc_before = getattr(src_value_node, "wsc_before", [" "])
                tracked_top.values[idx] = new_value_node


def _deep_merge_jsonobject(
    src_obj: JSONObject,
    live_dict: Mapping,
    path: str,
) -> None:
    """Merge ``live_dict`` (parsed Python view) into ``src_obj`` (model
    view) in place. Comments on src's existing keys are preserved by
    editing ``src_obj.values[idx]`` directly; live-only keys append a
    fresh :class:`KeyValuePair` with default formatting.
    """
    indent = _detect_indent(src_obj)
    for key, live_value in live_dict.items():
        sub_path = f"{path}.{key}"
        idx = _find_key_index(src_obj, key)
        if idx is None:
            new_key = DoubleQuotedString(characters=key, raw_value=json.dumps(key))
            new_key.wsc_before = [indent]
            new_val = _python_to_node(live_value)
            new_val.wsc_before = [" "]
            src_obj.keys.append(new_key)
            src_obj.values.append(new_val)
            continue
        src_value_node = src_obj.values[idx]
        match (src_value_node, live_value):
            case (JSONObject(), Mapping()):
                _deep_merge_jsonobject(src_value_node, live_value, sub_path)
            case (JSONObject(), _):
                raise MergeTypeMismatch(
                    f"type mismatch at {sub_path!r}: src is JSONObject, "
                    f"live is {type(live_value).__name__}"
                )
            case (_, Mapping()):
                raise MergeTypeMismatch(
                    f"type mismatch at {sub_path!r}: src is "
                    f"{type(src_value_node).__name__}, live is dict"
                )
            case _:
                # Scalar / list / mixed-shape: replace the whole node
                # while preserving the leading whitespace on the
                # KeyValuePair (comments on the replaced value node are
                # dropped — acceptable for live-wins overlay).
                new_val = _python_to_node(live_value)
                new_val.wsc_before = getattr(src_value_node, "wsc_before", [" "])
                src_obj.values[idx] = new_val


def strip_user_keys(text: str, key_names: list[str]) -> str:
    """Remove every entry in ``key_names`` from ``text``.

    Single-segment names match a literal top-level key (v1). Multi-segment
    nested paths (``" > "``-separated) descend into tracked's nested
    objects and remove the leaf in place. Missing intermediates / leaves
    are silent no-ops. Empty parent objects are NOT pruned — ``"[python]":
    {}`` is acceptable post-strip.

    Comments and formatting outside the removed entries are preserved.
    Trailing-comma cleanup and inter-entry whitespace collapse are
    handled by json-five's dumper.
    """
    model = loads(text, loader=ModelLoader())
    top = _require_top_object(model)
    for name in key_names:
        segments = _split_path(name)
        if len(segments) > 1:
            _strip_path(top, segments)
            continue
        idx = _find_key_index(top, name)
        if idx is None:
            continue
        del top.key_value_pairs[idx]
        del top.keys[idx]
        del top.values[idx]
    return dumps(model, dumper=ModelDumper())


def classify_jsonc_drift(
    src_text: str,
    live_text: str,
    key_names: list[str],
    deep_key_names: list[str] | None = None,
) -> tuple[list[str], list[str]]:
    """Return ``(expected, unexpected)`` lists of top-level key names that
    differ between parsed ``src_text`` and ``live_text``.

    Expected = the top-level key is covered by the preserve contract.
    Coverage is **position-precise** under nested paths: a key is
    expected iff every drift position beneath it is covered by either
    a ``deep_key_names`` entry (whole-subtree) or a ``key_names`` path
    starting with that key (per-leaf). Partial overlap → unexpected,
    matching v1 semantics. v1 flat names (no ``" > "``) treat the entire
    top-level entry as covered, identical to deep coverage.
    """
    src = parse_jsonc(src_text)
    live = parse_jsonc(live_text)
    if not isinstance(src, dict) or not isinstance(live, dict):
        return [], []
    deep_preserve = set(deep_key_names or [])
    flat_preserve = {n for n in key_names if PATH_SEPARATOR not in n}
    expected: list[str] = []
    unexpected: list[str] = []
    for key in sorted(set(src) | set(live)):
        if src.get(key) == live.get(key):
            continue
        if key in deep_preserve or key in flat_preserve:
            expected.append(key)
            continue
        preserved_positions = preserved_positions_for_top(key, key_names)
        if not preserved_positions:
            unexpected.append(key)
            continue
        drift_positions = _drift_positions(src.get(key), live.get(key))
        if drift_positions and drift_positions <= preserved_positions:
            expected.append(key)
        else:
            unexpected.append(key)
    return expected, unexpected


def preserved_positions_for_top(
    top_key: str, key_names: list[str]
) -> set[tuple[str, ...]]:
    """Return the set of position-tuples rooted at ``top_key`` covered by
    nested paths in ``key_names``.

    A path ``"[python] > editor.fontSize"`` whose first segment is
    ``[python]`` contributes the tuple ``("editor.fontSize",)``. v1 flat
    names contribute nothing; the caller handles those via the fast
    whole-key-expected branch.

    Public within the package: shared between
    :func:`classify_jsonc_drift` and :mod:`setforge.capture_wizard`'s
    deep-walk phase. Path-preserve coverage is inherently a JSONC-domain
    concept, so the implementation lives here and consumers import it.
    """
    positions: set[tuple[str, ...]] = set()
    for name in key_names:
        segments = _split_path(name)
        if len(segments) < 2:
            continue
        if segments[0] != top_key:
            continue
        positions.add(tuple(segments[1:]))
    return positions


def _drift_positions(src: Any, live: Any) -> set[tuple[str, ...]]:
    """Walk ``src`` vs ``live`` in parallel; return every leaf position
    where they differ.

    A "position" is a tuple of segments from the parent. The empty
    tuple means the values differ at the root of this walk (used when
    one side is a non-dict or absent). Dict-vs-dict descends key by key;
    one-side-non-dict yields the empty tuple (whole-subtree differs).
    """
    if src == live:
        return set()
    if not isinstance(src, dict) or not isinstance(live, dict):
        return {()}
    positions: set[tuple[str, ...]] = set()
    for key in set(src) | set(live):
        sub_src = src.get(key)
        sub_live = live.get(key)
        if sub_src == sub_live:
            continue
        sub_positions = _drift_positions(sub_src, sub_live)
        for tail in sub_positions:
            positions.add((key, *tail))
    return positions


def _overlay_path(
    tracked_top: JSONObject,
    live_value: Mapping[str, Any],
    segments: list[str],
    indent: str,
) -> None:
    """Splice live's leaf at ``segments`` into ``tracked_top`` in place.

    Walk ``live_value`` through ``segments[:-1]`` as dict descents and
    walk ``tracked_top`` through the same path as JSONObject descents.
    At the final segment, replace tracked's child with a fresh node from
    :func:`_python_to_node`; append a new :class:`KeyValuePair` if the
    leaf is missing in tracked's parent.

    Silent skips:

    - Live missing or non-dict at any intermediate (nothing to preserve).
    - Tracked missing intermediate (no auto-materialize per spec).
    - Tracked or live missing the leaf (matches v1 missing-key behavior
      on the tracked side; live side fed through ``_walk_dict_path``).

    Raises :class:`MergeTypeMismatch` when tracked has an intermediate
    that exists but is not a :class:`JSONObject`.
    """
    live_leaf = _walk_dict_path(live_value, segments[:-1])
    if not isinstance(live_leaf, dict):
        return
    leaf_key = segments[-1]
    if leaf_key not in live_leaf:
        return
    parent = _walk_jsonobject_path(tracked_top, segments[:-1])
    if parent is None:
        return
    parent_indent = _detect_indent(parent)
    new_value_node = _python_to_node(live_leaf[leaf_key])
    new_value_node.wsc_before = [" "]
    idx = _find_key_index(parent, leaf_key)
    if idx is not None:
        parent.values[idx] = new_value_node
        return
    new_key_node = DoubleQuotedString(
        characters=leaf_key, raw_value=json.dumps(leaf_key)
    )
    new_key_node.wsc_before = [parent_indent or indent]
    parent.keys.append(new_key_node)
    parent.values.append(new_value_node)


def _strip_path(tracked_top: JSONObject, segments: list[str]) -> None:
    """Remove the leaf at ``segments`` from ``tracked_top`` in place.

    Walks tracked through ``segments[:-1]``; missing intermediate or
    missing leaf is a silent no-op. Does NOT prune empty parent
    objects.
    """
    parent = _walk_jsonobject_path(tracked_top, segments[:-1])
    if parent is None:
        return
    leaf_key = segments[-1]
    idx = _find_key_index(parent, leaf_key)
    if idx is None:
        return
    del parent.key_value_pairs[idx]
    del parent.keys[idx]
    del parent.values[idx]


def _walk_jsonobject_path(
    top_obj: JSONObject, segments: list[str]
) -> JSONObject | None:
    """Descend ``top_obj`` through ``segments``, returning the JSONObject
    at the end of the walk.

    Empty ``segments`` returns ``top_obj`` itself. Missing intermediate
    returns ``None`` (silent skip). An intermediate that exists but is
    not a JSONObject raises :class:`MergeTypeMismatch` with the failing
    prefix.
    """
    node: JSONObject = top_obj
    walked: list[str] = []
    for seg in segments:
        idx = _find_key_index(node, seg)
        if idx is None:
            return None
        child = node.values[idx]
        walked.append(seg)
        if not isinstance(child, JSONObject):
            prefix = PATH_SEPARATOR.join(walked)
            raise MergeTypeMismatch(
                f"nested overlay requires JSONObject at {prefix!r}; "
                f"tracked has {type(child).__name__}"
            )
        node = child
    return node


def _walk_dict_path(value: Mapping[str, Any], segments: list[str]) -> Any:
    """Descend a plain Python mapping through ``segments``.

    Returns the value at the end of the walk, or ``None`` if any
    intermediate is missing or non-dict. Used for the live-side walk in
    :func:`_overlay_path` — live is parsed as a plain dict via
    :func:`parse_jsonc`, not the model API.
    """
    node: Any = value
    for seg in segments:
        if not isinstance(node, dict) or seg not in node:
            return None
        node = node[seg]
    return node


def _require_top_object(model: Any) -> JSONObject:
    top = model.value
    if not isinstance(top, JSONObject):
        raise ValueError("JSONC overlay/strip requires a top-level object")
    return top


def _find_key_index(top_obj: JSONObject, name: str) -> int | None:
    for i, key in enumerate(top_obj.keys):
        if _key_text(key) == name:
            return i
    return None


def _key_text(key_node: Any) -> str:
    """Return the key's literal characters regardless of quote style.

    JSON5 supports unquoted identifier keys and single-quoted strings in
    addition to JSONC's double-quoted; ``DoubleQuotedString`` /
    ``SingleQuotedString`` / ``Identifier`` all expose ``.characters``
    (or ``.name`` for identifiers) — but we only ever generate
    double-quoted, and VSCode emits double-quoted. For input we read,
    fall back to a string repr if the node shape is unexpected.
    """
    match key_node:
        case DoubleQuotedString(characters=c) | SingleQuotedString(characters=c):
            return str(c)
        case Identifier(name=n):
            return str(n)
        case _:
            return str(key_node)


def _detect_indent(top_obj: JSONObject) -> str:
    """Pick an indent prefix that matches existing siblings in ``top_obj``.

    Search order:
    1. ``leading_wsc`` (the whitespace right after the opening ``{``) —
       its trailing string element typically encodes the indent the
       parser saw before the first key.
    2. The trailing string element in any existing key's ``wsc_before``.
    3. Default: ``"\\n  "`` (LF + 2-space).
    """
    leading = getattr(top_obj, "leading_wsc", None) or []
    if leading and isinstance(leading[-1], str) and "\n" in leading[-1]:
        return leading[-1]
    for key in top_obj.keys:
        wsc = getattr(key, "wsc_before", None) or []
        if wsc and isinstance(wsc[-1], str) and "\n" in wsc[-1]:
            return wsc[-1]
    return "\n  "


def _python_to_node(value: Any) -> Any:
    """Convert a Python plain value into a JSON5 model leaf or container.

    Supports JSON5 scalars (``None`` / ``bool`` / ``int`` / ``float`` /
    ``str``) plus nested ``Mapping`` / ``list`` containers. Nested
    containers are built via :func:`_python_dict_to_jsonobject` and
    :func:`_python_list_to_jsonarray` (recursive).
    """
    match value:
        case None:
            return NullLiteral()
        case bool():
            # MUST precede ``case int()`` — isinstance(True, int) is True,
            # and class patterns use isinstance() semantics.
            return BooleanLiteral(value=value)
        case int():
            return Integer(raw_value=str(value))
        case float():
            return Float(raw_value=str(value))
        case str():
            return DoubleQuotedString(characters=value, raw_value=json.dumps(value))
        case Mapping():
            return _python_dict_to_jsonobject(value)
        case list():
            return _python_list_to_jsonarray(value)
        case _:
            raise TypeError(
                f"unsupported value type for JSONC overlay: {type(value).__name__}"
            )


def _python_dict_to_jsonobject(d: Mapping) -> JSONObject:
    """Build a :class:`JSONObject` with :class:`KeyValuePair` entries
    from a Python mapping.

    The model's ``__init__`` populates ``.keys`` and ``.values`` from
    its ``*key_value_pairs`` varargs; the ``key_value_pairs`` attribute
    on the resulting instance is a derived property, not a stored field.
    """
    kvps: list[KeyValuePair] = []
    for k, v in d.items():
        if not isinstance(k, str):
            raise TypeError(f"JSON object keys must be strings; got {type(k).__name__}")
        key_node = DoubleQuotedString(characters=k, raw_value=json.dumps(k))
        val_node = _python_to_node(v)
        kvps.append(KeyValuePair(key_node, val_node))
    return JSONObject(*kvps)


def _python_list_to_jsonarray(items: list) -> JSONArray:
    """Build a :class:`JSONArray` from a Python list. Each element is
    converted via :func:`_python_to_node` (recursive).
    """
    nodes = [_python_to_node(item) for item in items]
    return JSONArray(*nodes)
