"""JSONC overlay / strip / drift-classify for ``preserve_user_keys``.

VSCode ``settings.json`` files are JSONC (JSON with ``//`` and ``/* */``
comments and trailing commas). ruamel.yaml's round-trip mode can't parse
them, so the YAML preservation pipeline doesn't apply.

This module is a thin wrapper over :mod:`json5` (PyPI ``json-five``,
Apache 2.0). JSON5 is a strict superset of JSONC, so VSCode files parse
cleanly; the ``ModelLoader``/``ModelDumper`` pair preserves comments
and formatting on round-trip via ``.wsc_before`` / ``.wsc_after``
attributes attached to every node.

Scope (v1, per ``dotfiles-nen.6``):

- Literal top-level keys only. ``preserve_user_keys`` entries are NOT
  parsed as dotted paths — a key like
  ``"claudeCode.allowDangerouslySkipPermissions"`` is the literal whole
  string, matching VSCode's flat-with-dotted-names convention.
- Top-level user-key values may be any JSON5 scalar (string, number,
  boolean, null). Nested object/array values for user-keys are out of
  scope for v1; tracked as ``dotfiles-nen.6.1``.
- Standard JSONC syntax only: ``//``, ``/* */``, trailing commas. JSON5
  extras (unquoted keys, single-quoted strings, hex literals) are not
  generated by us; they parse but pass through untouched.

The exact json-five model API (node classes, field names) is upstream's
business — every reference to it stays inside this module so a future
breaking change in json-five requires a single-module fix.
"""

import json
from collections.abc import Mapping
from pathlib import Path
from typing import Any

from json5.dumper import ModelDumper, dumps
from json5.loader import ModelLoader, loads
from json5.model import (
    BooleanLiteral,
    DoubleQuotedString,
    Float,
    Identifier,
    Integer,
    JSONArray,
    JSONObject,
    KeyValuePair,
    NullLiteral,
    SingleQuotedString,
)

from my_setup.errors import MergeTypeMismatch


def is_jsonc_file(path: Path) -> bool:
    """True iff ``path`` should be treated as JSONC.

    Heuristic by extension: every ``.json`` file in this codebase is
    JSONC-capable (matches VSCode's behavior — ``.json`` is parsed as
    JSONC there). Tracked Claude ``settings.json`` is plain JSON in
    practice but still parses cleanly through the JSONC pipeline; no
    need for a content sniff.
    """
    return path.suffix == ".json"


def parse_jsonc(text: str) -> Any:
    """Parse JSONC into a plain Python value.

    Comments and formatting are dropped — this return is for drift
    classification (compare a tracked dict vs a live dict), not editing.
    Use :func:`overlay_user_keys` / :func:`strip_user_keys` for
    comment-preserving edits.
    """
    return loads(text)


def overlay_user_keys(
    tracked_text: str,
    live_text: str,
    key_names: list[str],
    deep_key_names: list[str] = (),
) -> str:
    """Splice live's top-level user-key values into tracked.

    Shallow mode (``key_names``): for each name, if live has it as a
    top-level key, set tracked's same key to live's value (replacing
    if already present, appending if not).

    Deep mode (``deep_key_names``): for each name, if live's value at
    that name is a JSON object AND tracked's value at the same name is
    also a JSON object, recursively deep-merge — tracked-only sub-keys
    survive, live-only added, scalars take live, lists whole-replaced,
    type mismatches at any depth raise :class:`MergeTypeMismatch`.

    Comments and formatting in tracked are preserved end-to-end across
    both modes. Top-level keys only — names match as literal strings
    against each top-level entry's key text.
    """
    tracked_model = loads(tracked_text, loader=ModelLoader())
    live_value = loads(live_text)
    if not isinstance(live_value, dict):
        return tracked_text
    tracked_top = _require_top_object(tracked_model)
    indent = _detect_indent(tracked_top)
    for name in key_names:
        if name not in live_value:
            continue
        new_value_node = _python_to_node(live_value[name])
        new_value_node.wsc_before = [" "]
        idx = _find_key_index(tracked_top, name)
        if idx is not None:
            tracked_top.values[idx] = new_value_node
        else:
            new_key_node = DoubleQuotedString(
                characters=name, raw_value=json.dumps(name)
            )
            new_key_node.wsc_before = [indent]
            tracked_top.keys.append(new_key_node)
            tracked_top.values.append(new_value_node)
    for name in deep_key_names:
        if name not in live_value:
            continue
        live_sub = live_value[name]
        idx = _find_key_index(tracked_top, name)
        if idx is None:
            new_value_node = _python_to_node(live_sub)
            new_value_node.wsc_before = [" "]
            new_key_node = DoubleQuotedString(
                characters=name, raw_value=json.dumps(name)
            )
            new_key_node.wsc_before = [indent]
            tracked_top.keys.append(new_key_node)
            tracked_top.values.append(new_value_node)
            continue
        src_value_node = tracked_top.values[idx]
        match (src_value_node, live_sub):
            case (JSONObject(), Mapping()):
                _deep_merge_jsonobject(src_value_node, live_sub, name)
            case (JSONObject(), _):
                raise MergeTypeMismatch(
                    f"deep-merge at {name!r} requires dict on both sides; "
                    f"live is {type(live_sub).__name__}"
                )
            case (_, Mapping()):
                raise MergeTypeMismatch(
                    f"deep-merge at {name!r} requires dict on both sides; "
                    f"src is {type(src_value_node).__name__}"
                )
            case _:
                # Mixed scalar/list at top-level deep-key: fall back to
                # whole-leaf replace — live wins, comments on the existing
                # value node are dropped (acceptable for live-wins overlay).
                new_value_node = _python_to_node(live_sub)
                new_value_node.wsc_before = getattr(src_value_node, "wsc_before", [" "])
                tracked_top.values[idx] = new_value_node
    return dumps(tracked_model, dumper=ModelDumper())


def _deep_merge_jsonobject(
    src_obj: JSONObject,
    live_dict: Mapping,
    path: str,
) -> None:
    """Merge ``live_dict`` (parsed Python view) into ``src_obj`` (model
    view) in place. Comments on src's existing keys are preserved by
    editing ``src_obj.values[idx]`` directly; live-only keys append a
    fresh :class:`KeyValuePair` with default formatting.
    """
    indent = _detect_indent(src_obj)
    for key, live_value in live_dict.items():
        sub_path = f"{path}.{key}"
        idx = _find_key_index(src_obj, key)
        if idx is None:
            new_key = DoubleQuotedString(characters=key, raw_value=json.dumps(key))
            new_key.wsc_before = [indent]
            new_val = _python_to_node(live_value)
            new_val.wsc_before = [" "]
            src_obj.keys.append(new_key)
            src_obj.values.append(new_val)
            continue
        src_value_node = src_obj.values[idx]
        match (src_value_node, live_value):
            case (JSONObject(), Mapping()):
                _deep_merge_jsonobject(src_value_node, live_value, sub_path)
            case (JSONObject(), _):
                raise MergeTypeMismatch(
                    f"type mismatch at {sub_path!r}: src is JSONObject, "
                    f"live is {type(live_value).__name__}"
                )
            case (_, Mapping()):
                raise MergeTypeMismatch(
                    f"type mismatch at {sub_path!r}: src is "
                    f"{type(src_value_node).__name__}, live is dict"
                )
            case _:
                # Scalar / list / mixed-shape: replace the whole node
                # while preserving the leading whitespace on the
                # KeyValuePair (comments on the replaced value node are
                # dropped — acceptable for live-wins overlay).
                new_val = _python_to_node(live_value)
                new_val.wsc_before = getattr(src_value_node, "wsc_before", [" "])
                src_obj.values[idx] = new_val


def strip_user_keys(text: str, key_names: list[str]) -> str:
    """Remove every top-level entry in ``key_names`` from ``text``.

    Comments and formatting outside the removed entries are preserved.
    Trailing-comma cleanup and inter-entry whitespace collapse are
    handled by json-five's dumper. Missing keys are silent no-ops.
    """
    model = loads(text, loader=ModelLoader())
    top = _require_top_object(model)
    for name in key_names:
        idx = _find_key_index(top, name)
        if idx is None:
            continue
        del top.key_value_pairs[idx]
        del top.keys[idx]
        del top.values[idx]
    return dumps(model, dumper=ModelDumper())


def classify_jsonc_drift(
    src_text: str,
    live_text: str,
    key_names: list[str],
    deep_key_names: list[str] = (),
) -> tuple[list[str], list[str]]:
    """Return ``(expected, unexpected)`` lists of top-level key names that
    differ between parsed ``src_text`` and ``live_text``.

    Expected = key is in ``key_names`` (shallow whole-leaf overlay
    contract) OR in ``deep_key_names`` (deep-merge overlay contract).
    Unexpected = drift on any other top-level key. Top-level only —
    nested differences within a deep-merge key still classify as a
    single "expected" entry (the deep-merge overlay reconciles them at
    deploy time).
    """
    src = parse_jsonc(src_text)
    live = parse_jsonc(live_text)
    if not isinstance(src, dict) or not isinstance(live, dict):
        return [], []
    preserve = set(key_names) | set(deep_key_names)
    expected: list[str] = []
    unexpected: list[str] = []
    for key in sorted(set(src) | set(live)):
        if src.get(key) == live.get(key):
            continue
        if key in preserve:
            expected.append(key)
        else:
            unexpected.append(key)
    return expected, unexpected


def _require_top_object(model: Any) -> JSONObject:
    top = model.value
    if not isinstance(top, JSONObject):
        raise ValueError("JSONC overlay/strip requires a top-level object")
    return top


def _find_key_index(top_obj: JSONObject, name: str) -> int | None:
    for i, key in enumerate(top_obj.keys):
        if _key_text(key) == name:
            return i
    return None


def _key_text(key_node: Any) -> str:
    """Return the key's literal characters regardless of quote style.

    JSON5 supports unquoted identifier keys and single-quoted strings in
    addition to JSONC's double-quoted; ``DoubleQuotedString`` /
    ``SingleQuotedString`` / ``Identifier`` all expose ``.characters``
    (or ``.name`` for identifiers) — but we only ever generate
    double-quoted, and VSCode emits double-quoted. For input we read,
    fall back to a string repr if the node shape is unexpected.
    """
    match key_node:
        case DoubleQuotedString(characters=c) | SingleQuotedString(characters=c):
            return str(c)
        case Identifier(name=n):
            return str(n)
        case _:
            return str(key_node)


def _detect_indent(top_obj: JSONObject) -> str:
    """Pick an indent prefix that matches existing siblings in ``top_obj``.

    Search order:
    1. ``leading_wsc`` (the whitespace right after the opening ``{``) —
       its trailing string element typically encodes the indent the
       parser saw before the first key.
    2. The trailing string element in any existing key's ``wsc_before``.
    3. Default: ``"\\n  "`` (LF + 2-space).
    """
    leading = getattr(top_obj, "leading_wsc", None) or []
    if leading and isinstance(leading[-1], str) and "\n" in leading[-1]:
        return leading[-1]
    for key in top_obj.keys:
        wsc = getattr(key, "wsc_before", None) or []
        if wsc and isinstance(wsc[-1], str) and "\n" in wsc[-1]:
            return wsc[-1]
    return "\n  "


def _python_to_node(value: Any) -> Any:
    """Convert a Python plain value into a JSON5 model leaf or container.

    Supports JSON5 scalars (``None`` / ``bool`` / ``int`` / ``float`` /
    ``str``) plus nested ``Mapping`` / ``list`` containers. Nested
    containers are built via :func:`_python_dict_to_jsonobject` and
    :func:`_python_list_to_jsonarray` (recursive).
    """
    match value:
        case None:
            return NullLiteral()
        case bool():
            # MUST precede ``case int()`` — isinstance(True, int) is True,
            # and class patterns use isinstance() semantics.
            return BooleanLiteral(value=value)
        case int():
            return Integer(raw_value=str(value))
        case float():
            return Float(raw_value=str(value))
        case str():
            return DoubleQuotedString(characters=value, raw_value=json.dumps(value))
        case Mapping():
            return _python_dict_to_jsonobject(value)
        case list():
            return _python_list_to_jsonarray(value)
        case _:
            raise TypeError(
                f"unsupported value type for JSONC overlay: {type(value).__name__}"
            )


def _python_dict_to_jsonobject(d: Mapping) -> JSONObject:
    """Build a :class:`JSONObject` with :class:`KeyValuePair` entries
    from a Python mapping.

    The model's ``__init__`` populates ``.keys`` and ``.values`` from
    its ``*key_value_pairs`` varargs; the ``key_value_pairs`` attribute
    on the resulting instance is a derived property, not a stored field.
    """
    kvps: list[KeyValuePair] = []
    for k, v in d.items():
        if not isinstance(k, str):
            raise TypeError(f"JSON object keys must be strings; got {type(k).__name__}")
        key_node = DoubleQuotedString(characters=k, raw_value=json.dumps(k))
        val_node = _python_to_node(v)
        kvps.append(KeyValuePair(key_node, val_node))
    return JSONObject(*kvps)


def _python_list_to_jsonarray(items: list) -> JSONArray:
    """Build a :class:`JSONArray` from a Python list. Each element is
    converted via :func:`_python_to_node` (recursive).
    """
    nodes = [_python_to_node(item) for item in items]
    return JSONArray(*nodes)
